benchmark_name = "DPP4"
pdb_id = "2HHA"
target_id = "CHEMBL284"
doc_id = "CHEMBL1137276"
assay_id = "CHEMBL856512"
ligand_resname = "3TP"
fragment_smiles = "CC(C)C(N)C(=O)N1CCCC1"
fragment_smiles_with_dummies = "*C1CCN(C(=O)C(N)C(*)*)C1"
require_fragment_match = true
require_pose_rmsd = true
filter_during_optimization = true
clip_reward_upper_bound = true
low_score = -8.778
high_score = -11.294
rmsd_threshold = 2.0
