benchmark_name = "ITK"
pdb_id = "3QGW"
target_id = "CHEMBL2959"
doc_id = "CHEMBL1765075"
assay_id = "CHEMBL1768448"
ligand_resname = "L7A"
fragment_smiles = "Cc1ccc(=O)[nH]c1"
fragment_smiles_with_dummies = "*c1c[nH]c(=O)c(*)c1"
require_fragment_match = true
require_pose_rmsd = true
filter_during_optimization = true
clip_reward_upper_bound = true
low_score = -7.67
high_score = -10.094
rmsd_threshold = 2.0
