benchmark_name: VEGFR2
pdb_id: 3VHE
target_id: CHEMBL279
doc_id: CHEMBL1250545
assay_id: CHEMBL1250641
ligand_resname: 42Q
fragment_smiles: c1ncc2[nH]ccc2n1
fragment_smiles_with_dummies: '*c1ncnc2ccn(*)c12'
require_fragment_match: true
require_pose_rmsd: true
filter_during_optimization: true
clip_reward_upper_bound: true
low_score: -9.564
high_score: -12.41
rmsd_threshold: 2.0
