benchmark_name: AKT1
pdb_id: 4EJN
target_id: CHEMBL4282
doc_id: CHEMBL2176970
assay_id: CHEMBL2186223
ligand_resname: 0R4
fragment_smiles: C1=CN=CC(C2=NC3=CC=CN=C3N2)=C1
low_score: -9.741
high_score: -14.342
rmsd_threshold: 2.0
